Initiate profiling ID early
perftools/xhgui-collector pull request #2
Opened 2017-08-22 10:34 UTC by AlarSuu

Initiate profiling id in `Xhgui_Saver` class constructor. That allows to use the same profiling ID throughout your request and profiler results can be easily mapped back to the areas, where this ID is used.

2017-08-22 12:00 UTC, lauripiisang requested changes

2017-08-22 12:00 UTC, lauripiisang commented on src/Xhgui/Profiles.php
> +	    $profile = $this->setProfilingId($profile);
Your tabulation is off -- this project uses spaces, you use tabs.

2017-08-22 12:00 UTC, lauripiisang commented on src/Xhgui/Profiles.php
> +	}
I think you could just turn this into a static `getCurrentProfileId` method that provides static variable (initialized to `new MongoId` on first call)
and then just call that from `insert` and you'll have the ability to call it from anywhere that requires it.

Does this make sense to you?

2017-08-22 12:00 UTC, lauripiisang commented on src/Xhgui/Saver.php
> +			        self::$lastProfilingId = new MongoId();
I don't think profiler.enable function should be called for anything except profiler enabling, as we won't know what lies there.

The user should be responsible for starting the profiler or take into account that asking for current profiling id while the profiler isn't running doesn't return anything meaningful (a MongoId that won't be persisted)

2017-08-22 17:29 UTC, markstory commented
I'm not really clear on how/why this feature is needed. In what scenarios do you need this?

2017-08-22 17:49 UTC, lauripiisang commented
@markstory This is so you can combine other profiling tools or manual profiling results with XHGUI results by having the profiling ID available.

If there was a way to get some meaningful ID from xhprof without disabling it, I'd probably use that.

2017-08-23 08:19 UTC, AlarSuu commented on src/Xhgui/Profiles.php
> +	    $profile = $this->setProfilingId($profile);
Fixed in commit: https://github.com/perftools/xhgui-collector/pull/2/commits/8e46f1019555a09323c52831f47b3a119683a3be

2017-08-23 08:19 UTC, AlarSuu commented on src/Xhgui/Profiles.php
> +	}
Makes sense: https://github.com/perftools/xhgui-collector/pull/2/commits/8e46f1019555a09323c52831f47b3a119683a3be#diff-4fe2f3dd6454d47d399256f2e1cbd7d7R38

2017-08-23 08:21 UTC, AlarSuu commented on src/Xhgui/Saver.php
> +			        self::$lastProfilingId = new MongoId();
Ok. And as I moved the static method into the `Profiling.php` class, then there are no changes in `Saver.php` class. I reverted my changes in a separate commit:
https://github.com/perftools/xhgui-collector/pull/2/commits/c68ee2256b65b0685279757ab7d0b98b9494b760

2017-08-23 11:57 UTC, lauripiisang approved these changes

2017-08-23 11:58 UTC, lauripiisang commented
I'd use `getCurrentProfileId` over `getLastProfilingId`, but that's a matter of preference I guess.

2017-08-23 11:58 UTC, merged